"""Curated leadership data for WWII seeding — 30+ leaders across all major combatant nations."""

from __future__ import annotations

LEADERS = [
    # ── Allied Political Leaders ──────────────────────────────────────────
    {
        "name": "Winston Churchill",
        "country": "United Kingdom",
        "title": "Prime Minister",
        "role_type": "political",
        "biography": "Winston Leonard Spencer Churchill served as Prime Minister of the United Kingdom from 1940 to 1945. His resolute leadership during the Battle of Britain and the Blitz galvanised the British people. A prolific writer and orator, he received the Nobel Prize in Literature in 1953. His strategic vision shaped Allied war policy through summits at Tehran, Yalta, and Potsdam.",
        "ideology": "Liberal Conservative, Anti-Appeasement",
        "influence_score": 97,
        "born_on": "1874-11-30",
        "died_on": "1965-01-24",
        "notable_quotes": [
            "We shall fight on the beaches, we shall fight on the landing grounds.",
            "Never in the field of human conflict was so much owed by so many to so few.",
            "If you are going through hell, keep going.",
        ],
        "key_operations": ["Battle of Britain", "Operation Overlord", "North African Campaign"],
    },
    {
        "name": "Franklin D. Roosevelt",
        "country": "USA",
        "title": "President of the United States",
        "role_type": "political",
        "biography": "Franklin Delano Roosevelt led the United States through the Great Depression and most of World War II. His Lend-Lease programme supplied Allied nations before American entry into the war. He authorised the Manhattan Project and helped establish the United Nations framework. He died in office on 12 April 1945, weeks before V-E Day.",
        "ideology": "New Deal Liberalism",
        "influence_score": 96,
        "born_on": "1882-01-30",
        "died_on": "1945-04-12",
        "notable_quotes": [
            "The only thing we have to fear is fear itself.",
            "Yesterday, December 7th, 1941 — a date which will live in infamy.",
            "We must be the great arsenal of democracy.",
        ],
        "key_operations": ["Lend-Lease Programme", "Manhattan Project", "Operation Torch"],
    },
    {
        "name": "Joseph Stalin",
        "country": "USSR",
        "title": "General Secretary of the Communist Party",
        "role_type": "political",
        "biography": "Joseph Vissarionovich Stalin directed the Soviet war effort from 1941 to 1945. Despite catastrophic early losses following Operation Barbarossa, he reorganised Soviet industry behind the Urals and oversaw the decisive victories at Stalingrad and Kursk. His Order No. 227 ('Not One Step Back') became emblematic of Soviet determination. He presided over the Red Army's advance to Berlin.",
        "ideology": "Marxism-Leninism, Soviet Socialism",
        "influence_score": 95,
        "born_on": "1878-12-18",
        "died_on": "1953-03-05",
        "notable_quotes": [
            "The death of one man is a tragedy. The death of millions is a statistic.",
            "Not one step back!",
        ],
        "key_operations": ["Battle of Stalingrad", "Battle of Kursk", "Operation Bagration"],
    },
    {
        "name": "Charles de Gaulle",
        "country": "France",
        "title": "Leader of Free France",
        "role_type": "political",
        "biography": "Charles André Joseph Marie de Gaulle led the Free French Forces from London after the fall of France in 1940. He maintained French sovereignty through diplomacy and organised resistance networks. His triumphant march down the Champs-Élysées on 26 August 1944 symbolised the liberation of Paris.",
        "ideology": "Gaullism, French Sovereignty",
        "influence_score": 85,
        "born_on": "1890-11-22",
        "died_on": "1970-11-09",
        "notable_quotes": [
            "France has lost a battle, but France has not lost the war.",
            "Paris! Paris outraged! Paris broken! Paris martyred! But Paris liberated!",
        ],
        "key_operations": ["Free French Forces", "Liberation of Paris"],
    },
    {
        "name": "Harry S. Truman",
        "country": "USA",
        "title": "President of the United States",
        "role_type": "political",
        "biography": "Harry S. Truman assumed the presidency upon Roosevelt's death on 12 April 1945. He made the decision to use atomic weapons against Hiroshima and Nagasaki, ending the Pacific War. He presided over the Potsdam Conference and the beginning of the Cold War.",
        "ideology": "New Deal Democrat",
        "influence_score": 88,
        "born_on": "1884-05-08",
        "died_on": "1972-12-26",
        "notable_quotes": [
            "The buck stops here.",
            "If you can't stand the heat, get out of the kitchen.",
        ],
        "key_operations": ["Atomic Bombings", "Potsdam Conference"],
    },
    # ── Axis Political Leaders ────────────────────────────────────────────
    {
        "name": "Adolf Hitler",
        "country": "Germany",
        "title": "Führer and Chancellor",
        "role_type": "political",
        "biography": "Adolf Hitler was the dictator of Nazi Germany from 1933 to 1945. He initiated World War II with the invasion of Poland on 1 September 1939. His aggressive expansionism, racial ideology, and micromanagement of military operations led to catastrophic losses on multiple fronts. He died by suicide in his Berlin bunker on 30 April 1945.",
        "ideology": "National Socialism, Fascism",
        "influence_score": 98,
        "born_on": "1889-04-20",
        "died_on": "1945-04-30",
        "notable_quotes": [],
        "key_operations": ["Operation Barbarossa", "Battle of Stalingrad", "Battle of Berlin"],
    },
    {
        "name": "Benito Mussolini",
        "country": "Italy",
        "title": "Il Duce",
        "role_type": "political",
        "biography": "Benito Amilcare Andrea Mussolini was the fascist dictator of Italy from 1922 to 1943. He entered WWII in June 1940, hoping for quick territorial gains. Italian defeats in North Africa and Greece weakened his position. He was deposed in July 1943 and later executed by partisans on 28 April 1945.",
        "ideology": "Fascism",
        "influence_score": 78,
        "born_on": "1883-07-29",
        "died_on": "1945-04-28",
        "notable_quotes": [],
        "key_operations": ["Invasion of Greece", "North African Campaign"],
    },
    {
        "name": "Hideki Tojo",
        "country": "Japan",
        "title": "Prime Minister of Japan",
        "role_type": "political",
        "biography": "Hideki Tōjō served as Prime Minister of Japan from October 1941 to July 1944. He was a key architect of Japan's entry into WWII and the attack on Pearl Harbor. After the war, he was convicted of war crimes by the International Military Tribunal for the Far East and executed in 1948.",
        "ideology": "Japanese Militarism, Imperialism",
        "influence_score": 80,
        "born_on": "1884-12-30",
        "died_on": "1948-12-23",
        "notable_quotes": [],
        "key_operations": ["Attack on Pearl Harbor", "Pacific War"],
    },
    # ── Allied Military Leaders ───────────────────────────────────────────
    {
        "name": "Dwight D. Eisenhower",
        "country": "USA",
        "title": "Supreme Allied Commander Europe",
        "role_type": "military",
        "biography": "Dwight David Eisenhower served as Supreme Commander of the Allied Expeditionary Force. He orchestrated the largest amphibious invasion in history — D-Day on 6 June 1944. His ability to manage a multinational coalition was exceptional. His 'Order of the Day' message for 6 June remains one of history's most famous military communiqués.",
        "ideology": "Coalition warfare doctrine",
        "influence_score": 96,
        "born_on": "1890-10-14",
        "died_on": "1969-03-28",
        "notable_quotes": [
            "Plans are worthless, but planning is everything.",
            "In preparing for battle I have always found that plans are useless, but planning is indispensable.",
        ],
        "key_operations": ["Operation Overlord", "Operation Torch", "Operation Neptune"],
    },
    {
        "name": "Georgy Zhukov",
        "country": "USSR",
        "title": "Marshal of the Soviet Union",
        "role_type": "military",
        "biography": "Georgy Konstantinovich Zhukov was the most decorated general officer in Soviet history. He led the defence of Moscow in 1941, co-directed the Stalingrad counteroffensive, commanded at Kursk, and led the final assault on Berlin. His mastery of deep battle operations and massed armour made him the war's most successful ground commander.",
        "ideology": "Soviet military doctrine",
        "influence_score": 95,
        "born_on": "1896-12-01",
        "died_on": "1974-06-18",
        "notable_quotes": [
            "If we come to a minefield, our infantry attacks exactly as if it were not there.",
        ],
        "key_operations": ["Battle of Moscow", "Battle of Stalingrad", "Battle of Kursk", "Battle of Berlin", "Operation Bagration"],
    },
    {
        "name": "Bernard Montgomery",
        "country": "United Kingdom",
        "title": "Field Marshal",
        "role_type": "military",
        "biography": "Bernard Law Montgomery commanded the British Eighth Army to victory at El Alamein in 1942 — the first major British land victory of the war. He later commanded Allied ground forces during D-Day and the advance through France. His methodical planning style contrasted with American commanders' preference for bold manoeuvre.",
        "ideology": "British combined arms doctrine",
        "influence_score": 90,
        "born_on": "1887-11-17",
        "died_on": "1976-03-24",
        "notable_quotes": [
            "Every soldier must know, before he goes into battle, how the little battle he is to fight fits into the larger picture.",
        ],
        "key_operations": ["Second Battle of El Alamein", "Operation Overlord", "Operation Market Garden"],
    },
    {
        "name": "Chester W. Nimitz",
        "country": "USA",
        "title": "Fleet Admiral, Commander in Chief Pacific",
        "role_type": "military",
        "biography": "Chester William Nimitz assumed command of the U.S. Pacific Fleet after Pearl Harbor. His strategic vision and trust in intelligence led to decisive victories at Midway and the Philippine Sea. He directed the island-hopping campaign that brought American forces to Japan's doorstep.",
        "ideology": "Naval warfare doctrine",
        "influence_score": 92,
        "born_on": "1885-02-24",
        "died_on": "1966-02-20",
        "notable_quotes": [
            "A ship is always referred to as 'she' because it costs so much to keep one in paint and powder.",
        ],
        "key_operations": ["Battle of Midway", "Battle of the Philippine Sea", "Battle of Leyte Gulf"],
    },
    {
        "name": "Douglas MacArthur",
        "country": "USA",
        "title": "General of the Army",
        "role_type": "military",
        "biography": "Douglas MacArthur commanded Allied forces in the Southwest Pacific. Forced to evacuate the Philippines in 1942, he famously declared 'I shall return' — and did, wading ashore at Leyte in October 1944. He accepted Japan's formal surrender aboard USS Missouri on 2 September 1945 and administered the occupation of Japan.",
        "ideology": "Pacific warfare doctrine",
        "influence_score": 93,
        "born_on": "1880-01-26",
        "died_on": "1964-04-05",
        "notable_quotes": [
            "I shall return.",
            "In war there is no substitute for victory.",
        ],
        "key_operations": ["Philippine Campaign", "Battle of Leyte Gulf", "Occupation of Japan"],
    },
    {
        "name": "George S. Patton",
        "country": "USA",
        "title": "General",
        "role_type": "military",
        "biography": "George Smith Patton Jr. was one of the most aggressive and successful Allied field commanders. He led the U.S. Seventh Army in the invasion of Sicily and the U.S. Third Army across France after D-Day. His rapid advance through the Lorraine and relief of Bastogne during the Battle of the Bulge demonstrated aggressive armoured warfare at its finest.",
        "ideology": "Offensive manoeuvre warfare",
        "influence_score": 91,
        "born_on": "1885-11-11",
        "died_on": "1945-12-21",
        "notable_quotes": [
            "A good plan violently executed now is better than a perfect plan executed next week.",
            "Lead me, follow me, or get out of my way.",
            "No bastard ever won a war by dying for his country. He won it by making the other poor dumb bastard die for his country.",
        ],
        "key_operations": ["Operation Husky", "Battle of the Bulge", "Lorraine Campaign"],
    },
    {
        "name": "Omar Bradley",
        "country": "USA",
        "title": "General of the Army",
        "role_type": "military",
        "biography": "Omar Nelson Bradley commanded the U.S. First Army during D-Day and later the 12th Army Group — the largest body of American soldiers ever to serve under a single field commander. Known as the 'Soldier's General', he was respected for his concern for troops' welfare and methodical approach.",
        "ideology": "Combined arms doctrine",
        "influence_score": 86,
        "born_on": "1893-02-12",
        "died_on": "1981-04-08",
        "notable_quotes": [
            "Amateurs talk about strategy. Professionals talk logistics.",
        ],
        "key_operations": ["Operation Overlord", "Battle of the Bulge", "Rhineland Campaign"],
    },
    {
        "name": "Konstantin Rokossovsky",
        "country": "USSR",
        "title": "Marshal of the Soviet Union",
        "role_type": "military",
        "biography": "Konstantin Konstantinovich Rokossovsky was a Soviet-Polish officer who rose to prominence during WWII. He commanded the Don Front at Stalingrad, led the Central Front at Kursk, and directed Operation Bagration which destroyed Army Group Centre. His operational brilliance earned him two Hero of the Soviet Union medals.",
        "ideology": "Soviet deep battle doctrine",
        "influence_score": 89,
        "born_on": "1896-12-21",
        "died_on": "1968-08-03",
        "notable_quotes": [],
        "key_operations": ["Battle of Stalingrad", "Battle of Kursk", "Operation Bagration"],
    },
    {
        "name": "Ivan Konev",
        "country": "USSR",
        "title": "Marshal of the Soviet Union",
        "role_type": "military",
        "biography": "Ivan Stepanovich Konev commanded the 1st Ukrainian Front during the final stages of the war. His forces competed with Zhukov's in the race to Berlin and liberated Prague. He was particularly skilled at large-scale encirclement operations.",
        "ideology": "Soviet manoeuvre doctrine",
        "influence_score": 87,
        "born_on": "1897-12-28",
        "died_on": "1973-05-21",
        "notable_quotes": [],
        "key_operations": ["Battle of Kursk", "Vistula-Oder Offensive", "Battle of Berlin"],
    },
    # ── Axis Military Leaders ─────────────────────────────────────────────
    {
        "name": "Erwin Rommel",
        "country": "Germany",
        "title": "Field Marshal",
        "role_type": "military",
        "biography": "Erwin Johannes Eugen Rommel, the 'Desert Fox', gained fame commanding the Afrika Korps in North Africa. His daring tactics and operational agility earned respect from both sides. Later assigned to defend the Atlantic Wall, he was implicated in the 20 July plot against Hitler and forced to take poison on 14 October 1944.",
        "ideology": "Mobile warfare doctrine",
        "influence_score": 93,
        "born_on": "1891-11-15",
        "died_on": "1944-10-14",
        "notable_quotes": [
            "Sweat saves blood, blood saves lives, but brains save both.",
            "In the absence of orders, go find something and kill it.",
            "The best form of welfare for the troops is first-rate training.",
        ],
        "key_operations": ["North African Campaign", "Second Battle of El Alamein", "Atlantic Wall"],
    },
    {
        "name": "Heinz Guderian",
        "country": "Germany",
        "title": "Generaloberst",
        "role_type": "military",
        "biography": "Heinz Wilhelm Guderian was the principal architect of Germany's panzer forces and Blitzkrieg doctrine. His armoured thrusts through the Ardennes in 1940 shattered Allied defences. He later served as Inspector-General of Armoured Troops and briefly as Chief of the Army General Staff.",
        "ideology": "Blitzkrieg, armoured warfare doctrine",
        "influence_score": 89,
        "born_on": "1888-06-17",
        "died_on": "1954-05-14",
        "notable_quotes": [
            "If the tanks succeed, then victory follows.",
            "You hit somebody with your fist and not with your fingers spread.",
        ],
        "key_operations": ["Fall of France", "Operation Barbarossa"],
    },
    {
        "name": "Erich von Manstein",
        "country": "Germany",
        "title": "Field Marshal",
        "role_type": "military",
        "biography": "Fritz Erich Georg Eduard von Lewinski, known as Erich von Manstein, was widely regarded as the Wehrmacht's finest strategist. He devised the Sichelschnitt plan that led to France's fall, commanded the siege of Sevastopol, and orchestrated the Third Battle of Kharkov — one of the war's most brilliant counterstrokes.",
        "ideology": "Operational manoeuvre warfare",
        "influence_score": 91,
        "born_on": "1887-11-24",
        "died_on": "1973-06-09",
        "notable_quotes": [],
        "key_operations": ["Fall of France", "Siege of Sevastopol", "Third Battle of Kharkov"],
    },
    {
        "name": "Karl Dönitz",
        "country": "Germany",
        "title": "Grand Admiral",
        "role_type": "military",
        "biography": "Karl Dönitz commanded the U-boat fleet and later became Commander-in-Chief of the Kriegsmarine. His wolf pack tactics devastated Allied shipping in the Battle of the Atlantic. Named Hitler's successor, he briefly served as head of state and oversaw Germany's unconditional surrender.",
        "ideology": "Naval attrition warfare",
        "influence_score": 84,
        "born_on": "1891-09-16",
        "died_on": "1980-12-24",
        "notable_quotes": [],
        "key_operations": ["Battle of the Atlantic", "U-boat Campaign"],
    },
    {
        "name": "Isoroku Yamamoto",
        "country": "Japan",
        "title": "Marshal Admiral",
        "role_type": "military",
        "biography": "Isoroku Yamamoto was Commander-in-Chief of the Combined Fleet of the Imperial Japanese Navy. He planned the attack on Pearl Harbor and the Battle of Midway. Despite personal reservations about war with the United States, he executed Japan's naval strategy aggressively. He was killed when his transport aircraft was ambushed by American P-38 fighters on 18 April 1943.",
        "ideology": "Carrier-centric naval warfare",
        "influence_score": 90,
        "born_on": "1884-04-04",
        "died_on": "1943-04-18",
        "notable_quotes": [
            "I fear all we have done is to awaken a sleeping giant and fill him with a terrible resolve.",
        ],
        "key_operations": ["Attack on Pearl Harbor", "Battle of Midway"],
    },
    {
        "name": "Tomoyuki Yamashita",
        "country": "Japan",
        "title": "General",
        "role_type": "military",
        "biography": "Tomoyuki Yamashita, the 'Tiger of Malaya', gained fame for his lightning conquest of Malaya and Singapore in 1942 — described as the worst British military disaster in history. He later commanded the defence of the Philippines in 1944-45. He was tried and executed for war crimes in 1946.",
        "ideology": "Japanese offensive doctrine",
        "influence_score": 82,
        "born_on": "1885-11-08",
        "died_on": "1946-02-23",
        "notable_quotes": [],
        "key_operations": ["Fall of Singapore", "Philippine Campaign"],
    },
    {
        "name": "Albert Kesselring",
        "country": "Germany",
        "title": "Field Marshal",
        "role_type": "military",
        "biography": "Albert Konrad Kesselring commanded German forces in the Mediterranean and Italian theaters. His defensive campaign in Italy — exploiting the peninsula's mountainous terrain through the Gustav Line, Gothic Line, and other fortified positions — delayed the Allied advance for nearly two years despite overwhelming Allied superiority.",
        "ideology": "Combined arms defensive doctrine",
        "influence_score": 85,
        "born_on": "1885-11-30",
        "died_on": "1960-07-16",
        "notable_quotes": [],
        "key_operations": ["Battle of Monte Cassino", "Italian Campaign", "Mediterranean Theater"],
    },
    {
        "name": "Friedrich Paulus",
        "country": "Germany",
        "title": "Field Marshal",
        "role_type": "military",
        "biography": "Friedrich Wilhelm Ernst Paulus commanded the German 6th Army at Stalingrad. Promoted to Field Marshal by Hitler (who expected him to commit suicide rather than surrender), he became the highest-ranking German officer ever to be taken prisoner when he surrendered on 31 January 1943.",
        "ideology": "Wehrmacht operational doctrine",
        "influence_score": 72,
        "born_on": "1890-09-23",
        "died_on": "1957-02-01",
        "notable_quotes": [],
        "key_operations": ["Battle of Stalingrad"],
    },
    # ── Additional Allied Commanders ──────────────────────────────────────
    {
        "name": "Louis Mountbatten",
        "country": "United Kingdom",
        "title": "Admiral, Supreme Allied Commander South East Asia",
        "role_type": "military",
        "biography": "Louis Francis Albert Victor Nicholas Mountbatten served as Supreme Allied Commander of South East Asia Command from 1943. He oversaw the reconquest of Burma and the defeat of Japanese forces in Southeast Asia. Earlier in the war he headed Combined Operations, planning commando raids and developing amphibious warfare techniques.",
        "ideology": "Combined operations doctrine",
        "influence_score": 83,
        "born_on": "1900-06-25",
        "died_on": "1979-08-27",
        "notable_quotes": [],
        "key_operations": ["Burma Campaign", "Combined Operations"],
    },
    {
        "name": "Chiang Kai-shek",
        "country": "China",
        "title": "Generalissimo",
        "role_type": "political",
        "biography": "Chiang Kai-shek led the Republic of China through eight years of war against Japan (1937-1945). Despite enormous casualties and territorial losses, Chinese resistance tied down over a million Japanese troops. He attended the Cairo Conference in 1943 alongside Roosevelt and Churchill.",
        "ideology": "Chinese Nationalism, Three Principles of the People",
        "influence_score": 82,
        "born_on": "1887-10-31",
        "died_on": "1975-04-05",
        "notable_quotes": [],
        "key_operations": ["Second Sino-Japanese War", "Burma Campaign"],
    },
    {
        "name": "William Slim",
        "country": "United Kingdom",
        "title": "Field Marshal",
        "role_type": "military",
        "biography": "William Joseph Slim commanded the British Fourteenth Army in Burma — the 'Forgotten Army'. He transformed a demoralised force into one that defeated the Japanese in the largest land battle fought by the British Empire, at Imphal-Kohima, and then advanced 600 miles to recapture Rangoon.",
        "ideology": "Combined arms jungle warfare",
        "influence_score": 86,
        "born_on": "1891-08-06",
        "died_on": "1970-12-14",
        "notable_quotes": [
            "When you go home, tell them of us and say, for your tomorrow, we gave our today.",
        ],
        "key_operations": ["Battle of Imphal", "Battle of Kohima", "Burma Campaign"],
    },
    {
        "name": "Władysław Anders",
        "country": "Poland",
        "title": "Lieutenant General",
        "role_type": "military",
        "biography": "Władysław Albert Anders led the Polish II Corps, formed from Polish prisoners released from Soviet labour camps. His corps fought with distinction in the Italian Campaign, most famously storming the ruins of Monte Cassino abbey in May 1944 when other Allied units had failed.",
        "ideology": "Polish independence",
        "influence_score": 75,
        "born_on": "1892-08-11",
        "died_on": "1970-05-12",
        "notable_quotes": [],
        "key_operations": ["Battle of Monte Cassino", "Italian Campaign"],
    },
]
