"""Curated battle data for WWII seeding — 25+ major engagements with accurate historical data."""

from __future__ import annotations

BATTLES = [
    # ── European Theater ──────────────────────────────────────────────────
    {
        "name": "Battle of France",
        "campaign": "Fall of France",
        "region": "Western Europe",
        "theater": "Europe",
        "location_name": "France, Belgium, Netherlands",
        "start_date": "1940-05-10",
        "end_date": "1940-06-25",
        "axis_forces": 3350000,
        "allied_forces": 3300000,
        "axis_casualties": 163000,
        "allied_casualties": 360000,
        "victor_side": "axis",
        "description": "Germany's Blitzkrieg shattered Allied defences in six weeks. Guderian's panzer thrust through the Ardennes bypassed the Maginot Line and split the Allied armies, leading to the evacuation at Dunkirk and France's armistice.",
        "latitude": 49.0,
        "longitude": 2.5,
    },
    {
        "name": "Battle of Britain",
        "campaign": "Defence of Britain",
        "region": "United Kingdom",
        "theater": "Europe",
        "location_name": "Southern England",
        "start_date": "1940-07-10",
        "end_date": "1940-10-31",
        "axis_forces": 2550,
        "allied_forces": 1963,
        "axis_casualties": 2585,
        "allied_casualties": 1547,
        "victor_side": "allies",
        "description": "The first major campaign fought entirely by air forces. The RAF's Fighter Command defeated the Luftwaffe's attempt to gain air superiority over Britain, forcing Hitler to indefinitely postpone Operation Sea Lion — the planned invasion of England.",
        "latitude": 51.1,
        "longitude": 1.3,
    },
    {
        "name": "Battle of Stalingrad",
        "campaign": "Eastern Front Offensive",
        "region": "Eastern Front",
        "theater": "Europe",
        "location_name": "Stalingrad, USSR",
        "start_date": "1942-08-23",
        "end_date": "1943-02-02",
        "axis_forces": 1040000,
        "allied_forces": 1143000,
        "axis_casualties": 868000,
        "allied_casualties": 1130000,
        "victor_side": "allies",
        "description": "The bloodiest battle in human history. Soviet forces encircled and destroyed the German 6th Army in Operation Uranus. Field Marshal Paulus's surrender marked the first time a German field marshal was captured and the decisive turning point of the Eastern Front.",
        "latitude": 48.708,
        "longitude": 44.513,
    },
    {
        "name": "Battle of Kursk",
        "campaign": "Eastern Front Offensive",
        "region": "Eastern Front",
        "theater": "Europe",
        "location_name": "Kursk, USSR",
        "start_date": "1943-07-05",
        "end_date": "1943-07-23",
        "axis_forces": 780000,
        "allied_forces": 1910000,
        "axis_casualties": 200000,
        "allied_casualties": 254000,
        "victor_side": "allies",
        "description": "The largest tank battle in history, involving over 6,000 tanks, 4,000 aircraft, and 2 million troops. Germany's last major offensive on the Eastern Front was defeated by prepared Soviet defences in depth, after which the strategic initiative permanently shifted to the Red Army.",
        "latitude": 51.73,
        "longitude": 36.19,
    },
    {
        "name": "Battle of Normandy",
        "campaign": "Western Front Liberation",
        "region": "Normandy",
        "theater": "Europe",
        "location_name": "Normandy, France",
        "start_date": "1944-06-06",
        "end_date": "1944-08-25",
        "axis_forces": 380000,
        "allied_forces": 1560000,
        "axis_casualties": 200000,
        "allied_casualties": 226386,
        "victor_side": "allies",
        "description": "D-Day and the subsequent campaign in Normandy opened the Western Front. The largest amphibious invasion in history landed 156,000 troops on five beaches. The breakout from the bocage at Operation Cobra and the encirclement at the Falaise Pocket destroyed the German defenders.",
        "latitude": 49.18,
        "longitude": -0.37,
    },
    {
        "name": "Battle of the Bulge",
        "campaign": "Ardennes Campaign",
        "region": "Ardennes",
        "theater": "Europe",
        "location_name": "Ardennes, Belgium/Luxembourg",
        "start_date": "1944-12-16",
        "end_date": "1945-01-25",
        "axis_forces": 406000,
        "allied_forces": 610000,
        "axis_casualties": 100000,
        "allied_casualties": 89500,
        "victor_side": "allies",
        "description": "Germany's last major offensive in Western Europe struck through the Ardennes forest, creating a 'bulge' in Allied lines. Despite initial surprise, American forces held critical road junctions at Bastogne and St. Vith, and Patton's Third Army relieved the siege. The offensive exhausted Germany's last strategic reserves.",
        "latitude": 50.05,
        "longitude": 5.72,
    },
    {
        "name": "Battle of Berlin",
        "campaign": "Fall of Germany",
        "region": "Berlin",
        "theater": "Europe",
        "location_name": "Berlin, Germany",
        "start_date": "1945-04-16",
        "end_date": "1945-05-02",
        "axis_forces": 766750,
        "allied_forces": 2500000,
        "axis_casualties": 325000,
        "allied_casualties": 352475,
        "victor_side": "allies",
        "description": "The final major offensive of the European war. Zhukov and Konev's armies encircled and stormed Berlin in brutal urban combat. Hitler committed suicide on 30 April; the Berlin garrison surrendered on 2 May. Germany's unconditional surrender followed on 8 May 1945.",
        "latitude": 52.52,
        "longitude": 13.405,
    },
    {
        "name": "Siege of Leningrad",
        "campaign": "Eastern Front Offensive",
        "region": "Eastern Front",
        "theater": "Europe",
        "location_name": "Leningrad (St. Petersburg), USSR",
        "start_date": "1941-09-08",
        "end_date": "1944-01-27",
        "axis_forces": 725000,
        "allied_forces": 930000,
        "axis_casualties": 580000,
        "allied_casualties": 1017881,
        "victor_side": "allies",
        "description": "The longest and most destructive siege in history lasted 872 days. An estimated 1.5 million civilians and soldiers died, most from starvation and cold. The city's survival became a symbol of Soviet endurance. The 'Road of Life' across frozen Lake Ladoga was the only supply route.",
        "latitude": 59.95,
        "longitude": 30.32,
    },
    # ── North African Theater ─────────────────────────────────────────────
    {
        "name": "Second Battle of El Alamein",
        "campaign": "North African Campaign",
        "region": "North Africa",
        "theater": "Africa",
        "location_name": "El Alamein, Egypt",
        "start_date": "1942-10-23",
        "end_date": "1942-11-11",
        "axis_forces": 116000,
        "allied_forces": 195000,
        "axis_casualties": 37000,
        "allied_casualties": 13560,
        "victor_side": "allies",
        "description": "Montgomery's Eighth Army defeated Rommel's Afrika Korps in a meticulously planned set-piece battle. Churchill later said, 'Before Alamein we never had a victory. After Alamein we never had a defeat.' The victory led to the Axis retreat across Libya and Tunisia.",
        "latitude": 30.83,
        "longitude": 28.95,
    },
    {
        "name": "Battle of Kasserine Pass",
        "campaign": "North African Campaign",
        "region": "North Africa",
        "theater": "Africa",
        "location_name": "Kasserine Pass, Tunisia",
        "start_date": "1943-02-19",
        "end_date": "1943-02-25",
        "axis_forces": 22000,
        "allied_forces": 30000,
        "axis_casualties": 2000,
        "allied_casualties": 10000,
        "victor_side": "axis",
        "description": "Rommel's forces inflicted a humiliating defeat on the inexperienced U.S. II Corps in their first major engagement against the Wehrmacht. The battle exposed serious deficiencies in American tactics, equipment, and command. It led to major reforms, including Patton's appointment to command II Corps.",
        "latitude": 35.17,
        "longitude": 8.73,
    },
    # ── Pacific Theater ───────────────────────────────────────────────────
    {
        "name": "Battle of Midway",
        "campaign": "Pacific Naval Campaign",
        "region": "Pacific",
        "theater": "Pacific",
        "location_name": "Midway Atoll",
        "start_date": "1942-06-04",
        "end_date": "1942-06-07",
        "axis_forces": 248,
        "allied_forces": 141,
        "axis_casualties": 3057,
        "allied_casualties": 307,
        "victor_side": "allies",
        "description": "The decisive naval battle of the Pacific. American codebreakers identified the Japanese target, allowing Nimitz to concentrate his outnumbered carriers. In five minutes on 4 June, dive bombers from USS Enterprise and Yorktown destroyed three Japanese carriers. Japan lost four fleet carriers and the strategic initiative in the Pacific.",
        "latitude": 28.21,
        "longitude": -177.37,
    },
    {
        "name": "Battle of Guadalcanal",
        "campaign": "Solomon Islands Campaign",
        "region": "Pacific",
        "theater": "Pacific",
        "location_name": "Guadalcanal, Solomon Islands",
        "start_date": "1942-08-07",
        "end_date": "1943-02-09",
        "axis_forces": 36200,
        "allied_forces": 60000,
        "axis_casualties": 31000,
        "allied_casualties": 7100,
        "victor_side": "allies",
        "description": "The first major Allied offensive against Japanese expansion. Six months of brutal jungle fighting, naval battles, and air combat culminated in Japanese withdrawal. It marked the transition from defensive to offensive operations in the Pacific.",
        "latitude": -9.44,
        "longitude": 160.04,
    },
    {
        "name": "Battle of Iwo Jima",
        "campaign": "Pacific Island Campaign",
        "region": "Pacific",
        "theater": "Pacific",
        "location_name": "Iwo Jima, Volcano Islands",
        "start_date": "1945-02-19",
        "end_date": "1945-03-26",
        "axis_forces": 21000,
        "allied_forces": 110000,
        "axis_casualties": 20703,
        "allied_casualties": 26038,
        "victor_side": "allies",
        "description": "One of the bloodiest battles in Marine Corps history. Japanese defenders had constructed a network of tunnels and fortifications across the volcanic island. The iconic photograph of Marines raising the flag on Mount Suribachi became one of the war's most recognized images.",
        "latitude": 24.78,
        "longitude": 141.32,
    },
    {
        "name": "Battle of Okinawa",
        "campaign": "Pacific Island Campaign",
        "region": "Pacific",
        "theater": "Pacific",
        "location_name": "Okinawa, Ryukyu Islands",
        "start_date": "1945-04-01",
        "end_date": "1945-06-22",
        "axis_forces": 130000,
        "allied_forces": 541000,
        "axis_casualties": 110071,
        "allied_casualties": 82000,
        "victor_side": "allies",
        "description": "The largest amphibious assault in the Pacific War. Fierce Japanese resistance, including mass kamikaze attacks, resulted in enormous casualties on both sides. The battle's costliness was a major factor in the decision to use atomic weapons against Japan.",
        "latitude": 26.5,
        "longitude": 127.97,
    },
    {
        "name": "Battle of Leyte Gulf",
        "campaign": "Philippine Liberation",
        "region": "Pacific",
        "theater": "Pacific",
        "location_name": "Leyte, Philippines",
        "start_date": "1944-10-23",
        "end_date": "1944-10-26",
        "axis_forces": 300,
        "allied_forces": 400,
        "axis_casualties": 12500,
        "allied_casualties": 3000,
        "victor_side": "allies",
        "description": "The largest naval battle in history, fought across four separate engagements. The Imperial Japanese Navy committed virtually its entire remaining fleet; the resulting defeat ended Japan as a viable naval power. The battle saw the first organised use of kamikaze tactics.",
        "latitude": 10.5,
        "longitude": 125.5,
    },
    {
        "name": "Battle of the Philippine Sea",
        "campaign": "Pacific Naval Campaign",
        "region": "Pacific",
        "theater": "Pacific",
        "location_name": "Philippine Sea",
        "start_date": "1944-06-19",
        "end_date": "1944-06-20",
        "axis_forces": 170,
        "allied_forces": 300,
        "axis_casualties": 3000,
        "allied_casualties": 109,
        "victor_side": "allies",
        "description": "The 'Great Marianas Turkey Shoot'. American carrier pilots and anti-aircraft gunners destroyed over 600 Japanese aircraft in two days. Japan lost three carriers and the irreplaceable core of its naval aviation, ensuring American air superiority for the rest of the war.",
        "latitude": 15.0,
        "longitude": 140.0,
    },
    # ── Mediterranean / Italian Theater ───────────────────────────────────
    {
        "name": "Battle of Monte Cassino",
        "campaign": "Italian Campaign",
        "region": "Italy",
        "theater": "Europe",
        "location_name": "Monte Cassino, Italy",
        "start_date": "1944-01-17",
        "end_date": "1944-05-18",
        "axis_forces": 80000,
        "allied_forces": 240000,
        "axis_casualties": 20000,
        "allied_casualties": 55000,
        "victor_side": "allies",
        "description": "Four bloody assaults were needed to breach the Gustav Line, anchored on the hilltop monastery of Monte Cassino. The Polish II Corps under General Anders finally captured the ruins in May 1944, opening the road to Rome. The controversial Allied bombing of the ancient Benedictine monastery remains debated.",
        "latitude": 41.49,
        "longitude": 13.81,
    },
    {
        "name": "Battle of Anzio",
        "campaign": "Italian Campaign",
        "region": "Italy",
        "theater": "Europe",
        "location_name": "Anzio, Italy",
        "start_date": "1944-01-22",
        "end_date": "1944-06-05",
        "axis_forces": 135000,
        "allied_forces": 150000,
        "axis_casualties": 27500,
        "allied_casualties": 43000,
        "victor_side": "allies",
        "description": "An amphibious landing behind German lines intended to outflank the Gustav Line. Initial surprise was squandered by cautious command, allowing the Germans to contain the beachhead for four months. Churchill remarked, 'I had hoped we were hurling a wildcat ashore. All we got was a stranded whale.'",
        "latitude": 41.45,
        "longitude": 12.62,
    },
    # ── Eastern Front (Additional) ────────────────────────────────────────
    {
        "name": "Battle of Moscow",
        "campaign": "Eastern Front Offensive",
        "region": "Eastern Front",
        "theater": "Europe",
        "location_name": "Moscow, USSR",
        "start_date": "1941-10-02",
        "end_date": "1942-01-07",
        "axis_forces": 1929000,
        "allied_forces": 1250000,
        "axis_casualties": 248000,
        "allied_casualties": 650000,
        "victor_side": "allies",
        "description": "Operation Typhoon — the German drive on Moscow — was halted in the suburbs of the Soviet capital. Zhukov's counteroffensive, using fresh Siberian divisions in brutal winter conditions, drove the Wehrmacht back up to 250 km. It was the first major German land defeat of WWII.",
        "latitude": 55.75,
        "longitude": 37.62,
    },
    {
        "name": "Battle of Smolensk",
        "campaign": "Eastern Front Offensive",
        "region": "Eastern Front",
        "theater": "Europe",
        "location_name": "Smolensk, USSR",
        "start_date": "1941-07-10",
        "end_date": "1941-09-10",
        "axis_forces": 430000,
        "allied_forces": 581600,
        "axis_casualties": 100000,
        "allied_casualties": 759974,
        "victor_side": "axis",
        "description": "A fierce battle that delayed the German advance on Moscow by two crucial months. Although the Germans captured Smolensk, Soviet resistance caused significant delays and casualties, foreshadowing the difficulties that would plague Operation Barbarossa.",
        "latitude": 54.78,
        "longitude": 32.05,
    },
    # ── Asian Theater ─────────────────────────────────────────────────────
    {
        "name": "Fall of Singapore",
        "campaign": "Malayan Campaign",
        "region": "Southeast Asia",
        "theater": "Asia",
        "location_name": "Singapore",
        "start_date": "1942-02-08",
        "end_date": "1942-02-15",
        "axis_forces": 36000,
        "allied_forces": 85000,
        "axis_casualties": 1714,
        "allied_casualties": 80000,
        "victor_side": "axis",
        "description": "Churchill called it 'the worst disaster and largest capitulation in British history'. Yamashita's forces, outnumbered more than two to one, bluffed the British garrison into surrendering by advancing aggressively on bicycles through the Malayan jungle, bypassing prepared defensive positions.",
        "latitude": 1.35,
        "longitude": 103.82,
    },
    {
        "name": "Battle of Imphal",
        "campaign": "Burma Campaign",
        "region": "Southeast Asia",
        "theater": "Asia",
        "location_name": "Imphal, India",
        "start_date": "1944-03-08",
        "end_date": "1944-07-22",
        "axis_forces": 92000,
        "allied_forces": 155000,
        "axis_casualties": 54879,
        "allied_casualties": 17500,
        "victor_side": "allies",
        "description": "Japan's U-Go offensive aimed to invade India but was decisively defeated. The twin battles of Imphal and Kohima are considered the turning point of the Burma Campaign. Japanese logistical failures led to catastrophic losses from disease and starvation.",
        "latitude": 24.82,
        "longitude": 93.95,
    },
    # ── Atlantic ──────────────────────────────────────────────────────────
    {
        "name": "Battle of the Atlantic",
        "campaign": "Atlantic Naval Campaign",
        "region": "Atlantic Ocean",
        "theater": "Europe",
        "location_name": "North Atlantic Ocean",
        "start_date": "1939-09-03",
        "end_date": "1945-05-08",
        "axis_forces": 1162,
        "allied_forces": 5000,
        "axis_casualties": 30000,
        "allied_casualties": 72200,
        "victor_side": "allies",
        "description": "The longest continuous military campaign of WWII. German U-boats sought to sever Britain's Atlantic supply lines. Over 3,500 Allied merchant ships were sunk. The introduction of escort carriers, long-range aircraft, improved radar, and the breaking of the Enigma cipher eventually turned the tide.",
        "latitude": 50.0,
        "longitude": -30.0,
    },
]
