"""Curated operations, campaigns, intelligence reports, war events, war crimes, and timeline data."""

from __future__ import annotations

CAMPAIGNS = [
    {"name": "Fall of France", "theater": "Europe", "region": "Western Europe", "start_date": "1940-05-10", "end_date": "1940-06-25", "outcome": "axis_victory", "strategic_value": 10, "description": "Germany's Blitzkrieg campaign that conquered France, Belgium, Netherlands, and Luxembourg in six weeks."},
    {"name": "Defence of Britain", "theater": "Europe", "region": "United Kingdom", "start_date": "1940-07-10", "end_date": "1941-05-11", "outcome": "allied_victory", "strategic_value": 10, "description": "Britain's successful defence against German air assault and the Blitz."},
    {"name": "Eastern Front Offensive", "theater": "Europe", "region": "Eastern Front", "start_date": "1941-06-22", "end_date": "1945-05-09", "outcome": "allied_victory", "strategic_value": 10, "description": "The largest and deadliest theater of WWII, spanning from Operation Barbarossa to the fall of Berlin."},
    {"name": "North African Campaign", "theater": "Africa", "region": "North Africa", "start_date": "1940-06-10", "end_date": "1943-05-13", "outcome": "allied_victory", "strategic_value": 8, "description": "Desert warfare across Libya, Egypt, and Tunisia between Axis and Allied forces."},
    {"name": "Western Front Liberation", "theater": "Europe", "region": "Normandy", "start_date": "1944-06-06", "end_date": "1945-05-08", "outcome": "allied_victory", "strategic_value": 10, "description": "Allied operations from D-Day through the liberation of Western Europe and advance into Germany."},
    {"name": "Italian Campaign", "theater": "Europe", "region": "Italy", "start_date": "1943-07-09", "end_date": "1945-05-02", "outcome": "allied_victory", "strategic_value": 7, "description": "Allied campaign up the Italian peninsula against fierce German defensive positions."},
    {"name": "Pacific Naval Campaign", "theater": "Pacific", "region": "Pacific", "start_date": "1941-12-07", "end_date": "1945-08-15", "outcome": "allied_victory", "strategic_value": 10, "description": "Carrier warfare and island-hopping across the vast Pacific Ocean."},
    {"name": "Pacific Island Campaign", "theater": "Pacific", "region": "Pacific", "start_date": "1942-08-07", "end_date": "1945-08-15", "outcome": "allied_victory", "strategic_value": 9, "description": "Amphibious assaults capturing strategic islands to bring Allied forces within striking distance of Japan."},
    {"name": "Solomon Islands Campaign", "theater": "Pacific", "region": "Pacific", "start_date": "1942-08-07", "end_date": "1943-11-21", "outcome": "allied_victory", "strategic_value": 7, "description": "Hard-fought campaign to halt Japanese expansion in the South Pacific."},
    {"name": "Philippine Liberation", "theater": "Pacific", "region": "Pacific", "start_date": "1944-10-20", "end_date": "1945-08-15", "outcome": "allied_victory", "strategic_value": 8, "description": "MacArthur's return to the Philippines and the liberation of the archipelago."},
    {"name": "Malayan Campaign", "theater": "Asia", "region": "Southeast Asia", "start_date": "1941-12-08", "end_date": "1942-02-15", "outcome": "axis_victory", "strategic_value": 8, "description": "Japan's lightning conquest of Malaya and Singapore."},
    {"name": "Burma Campaign", "theater": "Asia", "region": "Southeast Asia", "start_date": "1942-01-04", "end_date": "1945-08-15", "outcome": "allied_victory", "strategic_value": 7, "description": "Allied campaign to recapture Burma from Japanese forces, fought in extreme jungle conditions."},
    {"name": "Atlantic Naval Campaign", "theater": "Europe", "region": "Atlantic Ocean", "start_date": "1939-09-03", "end_date": "1945-05-08", "outcome": "allied_victory", "strategic_value": 10, "description": "The longest continuous campaign of WWII — the struggle for control of Atlantic shipping lanes."},
    {"name": "Ardennes Campaign", "theater": "Europe", "region": "Ardennes", "start_date": "1944-12-16", "end_date": "1945-01-25", "outcome": "allied_victory", "strategic_value": 8, "description": "Germany's last major offensive in the West, aimed at splitting Allied forces and capturing Antwerp."},
    {"name": "Fall of Germany", "theater": "Europe", "region": "Berlin", "start_date": "1945-01-12", "end_date": "1945-05-08", "outcome": "allied_victory", "strategic_value": 10, "description": "The final campaigns that crushed Nazi Germany from East and West simultaneously."},
    {"name": "Mediterranean Offensive", "theater": "Europe", "region": "Italy", "start_date": "1943-07-09", "end_date": "1943-09-17", "outcome": "allied_victory", "strategic_value": 7, "description": "Allied invasion of Sicily and southern Italy, forcing Italy's surrender."},
    {"name": "Deception Operations", "theater": "Europe", "region": "Western Europe", "start_date": "1943-01-01", "end_date": "1944-09-01", "outcome": "allied_victory", "strategic_value": 6, "description": "Allied strategic deception campaigns including Bodyguard, Fortitude, and Mincemeat."},
]

OPERATIONS = [
    {"name": "Operation Overlord", "code_name": "OVERLORD", "campaign": "Western Front Liberation", "region": "Normandy", "side": "allies", "outcome": "success", "start_date": "1944-06-06", "end_date": "1944-08-25", "objective": "Establish a Western Front lodgement in Normandy.", "description": "The Allied invasion of Normandy — the largest amphibious operation in history. 156,000 troops landed on five beaches on D-Day, supported by 11,590 aircraft and 6,939 vessels.", "analysis": "Combined naval, air, and land operation supported by elaborate deception planning (Operation Fortitude). Success depended on weather windows, airborne operations, and naval fire support.", "intelligence_notes": "ULTRA decrypts provided crucial intelligence about German dispositions. Operation Fortitude successfully fixed German reserves away from the landing beaches."},
    {"name": "Operation Barbarossa", "code_name": "BARBAROSSA", "campaign": "Eastern Front Offensive", "region": "Eastern Front", "side": "axis", "outcome": "failure", "start_date": "1941-06-22", "end_date": "1941-12-05", "objective": "Destroy the Soviet Union in a rapid campaign before winter.", "description": "The largest military operation in history. 3.8 million Axis troops invaded the USSR along a 2,900 km front. Despite spectacular initial gains, the campaign failed to achieve its objectives before the onset of winter.", "analysis": "Logistical overextension, underestimation of Soviet reserves, and the onset of the Russian winter combined to halt the Axis advance short of Moscow.", "intelligence_notes": "Stalin ignored multiple intelligence warnings of the impending invasion, including reports from Richard Sorge in Tokyo."},
    {"name": "Operation Torch", "code_name": "TORCH", "campaign": "North African Campaign", "region": "North Africa", "side": "allies", "outcome": "success", "start_date": "1942-11-08", "end_date": "1943-05-13", "objective": "Secure French North Africa and attack Axis forces from the west.", "description": "Anglo-American landings in Morocco and Algeria marked the first major Allied amphibious operation of the war. The campaign eventually trapped Axis forces in Tunisia.", "analysis": "Political complexity of dealing with Vichy French forces. Combined with Montgomery's advance from the east after El Alamein, it created a strategic pincer.", "intelligence_notes": "Intelligence negotiations with French officers in North Africa facilitated reduced resistance at landing sites."},
    {"name": "Operation Husky", "code_name": "HUSKY", "campaign": "Mediterranean Offensive", "region": "Italy", "side": "allies", "outcome": "success", "start_date": "1943-07-09", "end_date": "1943-08-17", "objective": "Capture Sicily and open sea lanes through the Mediterranean.", "description": "The Allied invasion of Sicily, involving 160,000 troops, 600 tanks, and 2,500 aircraft. The campaign led directly to the fall of Mussolini and Italy's armistice.", "analysis": "Amphibious and airborne operations supported by naval gunfire. The campaign demonstrated improved Allied coordination but also revealed inter-service friction.", "intelligence_notes": "Operation Mincemeat — a deception using a dead body with false documents — successfully diverted German attention to Sardinia and Greece."},
    {"name": "Operation Market Garden", "code_name": "MARKET GARDEN", "campaign": "Western Front Liberation", "region": "Netherlands", "side": "allies", "outcome": "failure", "start_date": "1944-09-17", "end_date": "1944-09-25", "objective": "Seize key bridges across the Rhine and outflank the Siegfried Line.", "description": "The largest airborne operation in history. Three airborne divisions dropped to capture bridges at Eindhoven, Nijmegen, and Arnhem. The ground advance failed to reach the British 1st Airborne at Arnhem in time, resulting in its near-destruction.", "analysis": "Overambitious planning, insufficient attention to intelligence about SS Panzer divisions refitting near Arnhem, and a single-axis ground advance doomed the operation.", "intelligence_notes": "Polish intelligence officer Sosabowski and Dutch resistance correctly warned of German armour near Arnhem. These warnings were dismissed."},
    {"name": "Operation Bagration", "code_name": "BAGRATION", "campaign": "Eastern Front Offensive", "region": "Eastern Front", "side": "allies", "outcome": "success", "start_date": "1944-06-23", "end_date": "1944-08-19", "objective": "Destroy German Army Group Centre in Byelorussia.", "description": "A massive Soviet summer offensive that destroyed 28 of Army Group Centre's 34 divisions. The Wehrmacht suffered 300,000-400,000 casualties — a catastrophe exceeding Stalingrad. Soviet forces advanced 600 km in two months.", "analysis": "Masterful use of maskirovka (military deception), deep operations doctrine, and overwhelming force concentration. Timed to coincide with D-Day, it prevented German reserves from reinforcing Normandy.", "intelligence_notes": "Soviet deception convinced the Germans the main blow would fall in Ukraine, achieving strategic surprise despite massive troop concentrations."},
    {"name": "Operation Fortitude", "code_name": "FORTITUDE", "campaign": "Deception Operations", "region": "Western Europe", "side": "allies", "outcome": "success", "start_date": "1944-01-01", "end_date": "1944-09-01", "objective": "Deceive Germany about the location and timing of the Normandy invasion.", "description": "The most complex and successful military deception in history. Fortitude South created a fictional First United States Army Group under Patton, threatening Pas-de-Calais. Fortitude North simulated a threat to Norway.", "analysis": "Double agents from the XX Committee, fake radio traffic, dummy equipment, and deliberate intelligence leaks convinced Hitler to hold 15 divisions in the Pas-de-Calais area for weeks after D-Day.", "intelligence_notes": "Agents Garbo and Brutus were central to feeding false intelligence to the Abwehr. The operation exploited Germany's trust in compromised intelligence networks."},
    {"name": "Operation Neptune", "code_name": "NEPTUNE", "campaign": "Western Front Liberation", "region": "Normandy", "side": "allies", "outcome": "success", "start_date": "1944-06-06", "end_date": "1944-06-30", "objective": "Naval component of Operation Overlord — transport and support the amphibious landings.", "description": "The largest naval operation in history. 6,939 vessels delivered 156,000 troops to five Normandy beaches on D-Day, supported by naval bombardment and minesweeping operations.", "analysis": "Meticulous planning of naval fire support, obstacle clearance, and supply logistics. Mulberry harbours provided artificial port facilities until Cherbourg was captured.", "intelligence_notes": "Hydrographic reconnaissance by midget submarines and beach reconnaissance teams provided critical data on tides, obstacles, and beach gradients."},
    {"name": "Operation Cobra", "code_name": "COBRA", "campaign": "Western Front Liberation", "region": "Normandy", "side": "allies", "outcome": "success", "start_date": "1944-07-25", "end_date": "1944-07-31", "objective": "Break out of the Normandy bocage.", "description": "A concentrated armoured breakthrough preceded by massive carpet bombing. Patton's Third Army poured through the gap and raced across France, ending the grinding attrition of the Normandy hedgerows.", "analysis": "Demonstrated the effectiveness of concentrated air-ground coordination. Some friendly fire casualties from carpet bombing marred the operation.", "intelligence_notes": "ULTRA intercepts confirmed that German reserves were committed piecemeal, validating the breakout timing."},
    {"name": "Operation Uranus", "code_name": "URANUS", "campaign": "Eastern Front Offensive", "region": "Eastern Front", "side": "allies", "outcome": "success", "start_date": "1942-11-19", "end_date": "1942-11-23", "objective": "Encircle the German 6th Army at Stalingrad.", "description": "A brilliant Soviet pincer operation that struck the weak Romanian flanks north and south of Stalingrad. Within four days, Soviet forces linked up at Kalach, trapping 290,000 Axis troops in the Stalingrad pocket.", "analysis": "Exploited the extended and thinly-held flanks manned by less capable Axis allies. Demonstrated Soviet mastery of deep operations at the operational level.", "intelligence_notes": "German intelligence failed to detect the massive Soviet build-up on their flanks despite aerial reconnaissance."},
    {"name": "Operation Citadel", "code_name": "CITADEL", "campaign": "Eastern Front Offensive", "region": "Eastern Front", "side": "axis", "outcome": "failure", "start_date": "1943-07-05", "end_date": "1943-07-16", "objective": "Eliminate the Kursk salient and destroy Soviet armoured reserves.", "description": "Germany's last major strategic offensive on the Eastern Front. Despite deploying new Tiger and Panther tanks, the attack was defeated by layered Soviet defences in depth. The Battle of Prokhorovka saw the largest tank engagement in history.", "analysis": "Soviet foreknowledge from ULTRA and the Lucy spy ring allowed preparation of massive defensive belts. Delayed start gave Soviets additional preparation time.", "intelligence_notes": "ULTRA decrypts of German signals provided the Soviets (via British intelligence) with detailed knowledge of German intentions and order of battle."},
    {"name": "Operation Downfall", "code_name": "DOWNFALL", "campaign": "Pacific Island Campaign", "region": "Pacific", "side": "allies", "outcome": "cancelled", "start_date": "1945-11-01", "end_date": "1946-03-01", "objective": "Invade and occupy the Japanese home islands.", "description": "The planned Allied invasion of Japan in two phases: Operation Olympic (Kyushu, November 1945) and Operation Coronet (Honshu, March 1946). Estimated to cost 500,000-1,000,000 Allied casualties. Rendered unnecessary by the atomic bombings and Japan's surrender.", "analysis": "The massive projected casualties influenced the decision to use atomic weapons. Japan had correctly anticipated the landing beaches and was massing kamikaze forces.", "intelligence_notes": "MAGIC intercepts revealed Japan's strategy of concentrating forces on Kyushu, raising casualty estimates significantly."},
]

INTELLIGENCE_REPORTS = [
    {"nation": "United Kingdom", "region": "Europe", "report_date": "1944-05-28T06:30:00", "classification": "top_secret", "source_type": "signals_intercept", "report_type": "force_posture", "content": "ULTRA decrypts indicate German reserves remain concentrated near Pas-de-Calais. Panzer Lehr Division identified south of Caen. No indication 15th Army has been placed on alert for Normandy sector.", "decoded": True, "confidence_level": 0.93, "source_reference": "Bletchley Park / Hut 6"},
    {"nation": "Germany", "region": "Eastern Front", "report_date": "1942-11-12T14:00:00", "classification": "secret", "source_type": "field_report", "report_type": "logistics", "content": "Fuel shortfalls and stretched railheads are degrading operational tempo near Stalingrad. 6th Army supply convoys subject to partisan interdiction. Von Paulus reports ammunition reserves at 40% of required levels.", "decoded": False, "confidence_level": 0.78, "source_reference": "Army Group South logistics dossier"},
    {"nation": "USA", "region": "Pacific", "report_date": "1942-05-27T09:00:00", "classification": "top_secret", "source_type": "signals_intercept", "report_type": "strategic_warning", "content": "MAGIC intercepts confirm Japanese Combined Fleet sortie towards objective 'AF' — confirmed as Midway Atoll via water supply deception. Four fleet carriers identified: Akagi, Kaga, Soryu, Hiryu. Strike date estimated 4-5 June.", "decoded": True, "confidence_level": 0.95, "source_reference": "Station HYPO / OP-20-G"},
    {"nation": "United Kingdom", "region": "North Africa", "report_date": "1942-10-15T11:30:00", "classification": "secret", "source_type": "signals_intercept", "report_type": "enemy_logistics", "content": "ULTRA reveals Rommel's fuel situation critical. Tanker shipments from Italy subject to RAF and RN interdiction. Afrika Korps tank strength below 50% of establishment. Montgomery authorised to proceed with El Alamein offensive.", "decoded": True, "confidence_level": 0.91, "source_reference": "Bletchley Park / Hut 3"},
    {"nation": "USSR", "region": "Eastern Front", "report_date": "1941-06-15T08:00:00", "classification": "top_secret", "source_type": "human_intelligence", "report_type": "strategic_warning", "content": "Richard Sorge reports from Tokyo: German invasion of the Soviet Union imminent. Estimated date between 20-22 June 1941. Full-scale attack along entire western frontier. Warning dismissed by Stalin as provocation.", "decoded": True, "confidence_level": 0.88, "source_reference": "GRU Agent Ramsay (Sorge network)"},
    {"nation": "United Kingdom", "region": "Europe", "report_date": "1943-06-15T16:00:00", "classification": "secret", "source_type": "signals_intercept", "report_type": "order_of_battle", "content": "ULTRA confirms presence of 2nd SS Panzer Corps refitting near Arnhem area. Formation includes 9th and 10th SS Panzer Divisions. Assessment: divisions at 30-50% combat effectiveness but contain experienced cadres.", "decoded": True, "confidence_level": 0.85, "source_reference": "Bletchley Park / Hut 3"},
    {"nation": "Germany", "region": "Europe", "report_date": "1944-06-05T22:00:00", "classification": "secret", "source_type": "field_report", "report_type": "weather_assessment", "content": "Luftwaffe meteorological service forecasts continued poor weather over English Channel 5-7 June. Assessment: Allied invasion unlikely during this window. Rommel departed for Germany. Several division commanders attending war games in Rennes.", "decoded": False, "confidence_level": 0.72, "source_reference": "OKW daily intelligence summary"},
    {"nation": "USA", "region": "Pacific", "report_date": "1945-03-15T10:00:00", "classification": "top_secret", "source_type": "signals_intercept", "report_type": "strategic_assessment", "content": "MAGIC intercepts of Japanese diplomatic cables reveal Imperial Conference considering peace terms via Soviet mediation. Military faction continues to dominate, insisting on 'decisive battle' strategy for homeland defence. Ketsu-Go plan identifies Kyushu as primary expected invasion target.", "decoded": True, "confidence_level": 0.90, "source_reference": "Arlington Hall / SIS"},
    {"nation": "United Kingdom", "region": "Atlantic Ocean", "report_date": "1943-03-20T07:30:00", "classification": "top_secret", "source_type": "signals_intercept", "report_type": "naval_operations", "content": "Bletchley Park regains ability to read U-boat Triton cipher after 10-month blackout. Current U-boat dispositions in North Atlantic identified. BdU deploying wolfpack groups STAR and DRANGER against convoy ONS-5.", "decoded": True, "confidence_level": 0.92, "source_reference": "Bletchley Park / Hut 8"},
    {"nation": "Germany", "region": "Eastern Front", "report_date": "1943-06-20T14:00:00", "classification": "secret", "source_type": "aerial_reconnaissance", "report_type": "defensive_assessment", "content": "Luftwaffe reconnaissance reveals extensive Soviet defensive preparations in Kursk salient. Multiple layered trench systems, minefields estimated at 2,500 mines per kilometre of front. Anti-tank positions in unprecedented depth. Assessment: Operation Citadel faces prepared defences.", "decoded": False, "confidence_level": 0.82, "source_reference": "Luftflotte 4 reconnaissance wing"},
    {"nation": "USSR", "region": "Eastern Front", "report_date": "1943-04-12T11:00:00", "classification": "top_secret", "source_type": "human_intelligence", "report_type": "strategic_warning", "content": "Lucy spy ring in Switzerland reports detailed German operational plans for Kursk offensive (Operation Citadel). German attack to employ pincer movement against Kursk salient with 17 panzer and 3 panzergrenadier divisions. New Tiger and Panther tanks to be committed in strength.", "decoded": True, "confidence_level": 0.89, "source_reference": "GRU via Lucy ring (Rudolf Rössler)"},
    {"nation": "United Kingdom", "region": "Europe", "report_date": "1944-01-20T09:00:00", "classification": "top_secret", "source_type": "counterintelligence", "report_type": "deception_assessment", "content": "XX Committee reports Agent GARBO has been awarded Iron Cross by Abwehr for intelligence services. This confirms continued German trust in GARBO network. Double-Cross deception channels validated for use in Operation Fortitude.", "decoded": True, "confidence_level": 0.95, "source_reference": "MI5 B1a Section / XX Committee"},
]

WAR_EVENTS = [
    {"event_type": "political", "name": "German Invasion of Poland", "event_date": "1939-09-01", "end_date": "1939-10-06", "region": "Eastern Front", "summary": "Germany invaded Poland, triggering declarations of war from Britain and France. The campaign introduced Blitzkrieg tactics.", "source": "curated"},
    {"event_type": "political", "name": "Fall of France Armistice", "event_date": "1940-06-22", "region": "Western Europe", "summary": "France signed an armistice with Germany at Compiègne, in the same railway carriage used for the 1918 armistice.", "source": "curated"},
    {"event_type": "political", "name": "Attack on Pearl Harbor", "event_date": "1941-12-07", "region": "Pacific", "summary": "Japan's surprise attack on the U.S. Pacific Fleet at Pearl Harbor brought the United States into WWII. 2,403 Americans were killed and 8 battleships damaged or destroyed.", "source": "curated"},
    {"event_type": "political", "name": "Germany Declares War on USA", "event_date": "1941-12-11", "region": "Europe", "summary": "Hitler declared war on the United States four days after Pearl Harbor, unifying the European and Pacific wars.", "source": "curated"},
    {"event_type": "political", "name": "Italian Armistice", "event_date": "1943-09-08", "region": "Italy", "summary": "Italy surrendered to the Allies following the fall of Mussolini and the invasion of Sicily. Germany occupied northern Italy.", "source": "curated"},
    {"event_type": "political", "name": "D-Day", "event_date": "1944-06-06", "region": "Normandy", "summary": "156,000 Allied troops landed on five Normandy beaches in the largest amphibious invasion in history, opening a Western Front in Europe.", "source": "curated"},
    {"event_type": "political", "name": "Liberation of Paris", "event_date": "1944-08-25", "region": "Western Europe", "summary": "French and American forces liberated Paris after four years of German occupation. De Gaulle marched down the Champs-Élysées.", "source": "curated"},
    {"event_type": "political", "name": "V-E Day", "event_date": "1945-05-08", "region": "Berlin", "summary": "Germany's unconditional surrender ended the war in Europe. Celebrations erupted across Allied nations.", "source": "curated"},
    {"event_type": "political", "name": "Atomic Bombing of Hiroshima", "event_date": "1945-08-06", "region": "Pacific", "summary": "The B-29 'Enola Gay' dropped 'Little Boy', the first atomic weapon used in combat, on Hiroshima. An estimated 80,000 people were killed immediately.", "source": "curated"},
    {"event_type": "political", "name": "Atomic Bombing of Nagasaki", "event_date": "1945-08-09", "region": "Pacific", "summary": "The second atomic bomb, 'Fat Man', was dropped on Nagasaki, killing approximately 40,000 people immediately.", "source": "curated"},
    {"event_type": "political", "name": "Japan Surrenders (V-J Day)", "event_date": "1945-09-02", "region": "Pacific", "summary": "Japan formally surrendered aboard USS Missouri in Tokyo Bay, ending World War II after six years of global conflict.", "source": "curated"},
    {"event_type": "political", "name": "Yalta Conference", "event_date": "1945-02-04", "end_date": "1945-02-11", "region": "Eastern Front", "summary": "Roosevelt, Churchill, and Stalin met at Yalta in Crimea to plan the postwar reorganisation of Europe.", "source": "curated"},
    {"event_type": "political", "name": "Potsdam Conference", "event_date": "1945-07-17", "end_date": "1945-08-02", "region": "Berlin", "summary": "Truman, Churchill (then Attlee), and Stalin met to discuss postwar administration of Germany and the ultimatum to Japan.", "source": "curated"},
    {"event_type": "war_crime", "name": "Oradour-sur-Glane massacre", "event_date": "1944-06-10", "region": "Western Europe", "summary": "Mass killing of 643 civilians by 2nd SS Panzer Division Das Reich in occupied France.", "source": "curated"},
    {"event_type": "war_crime", "name": "Malmedy massacre", "event_date": "1944-12-17", "region": "Ardennes", "summary": "Waffen-SS troops executed 84 American prisoners of war near Malmedy, Belgium during the Battle of the Bulge.", "source": "curated"},
    {"event_type": "war_crime", "name": "Bataan Death March", "event_date": "1942-04-09", "region": "Pacific", "summary": "Japanese forces forced 60,000-80,000 Filipino and American POWs to march 65 miles to prison camps. An estimated 6,000-18,000 did not survive.", "source": "curated"},
    {"event_type": "war_crime", "name": "Rape of Nanking", "event_date": "1937-12-13", "end_date": "1938-01-31", "region": "Southeast Asia", "summary": "Japanese troops perpetrated mass murder, rape, and looting in the Chinese capital of Nanking. Estimated 200,000-300,000 killed.", "source": "curated"},
    {"event_type": "war_crime", "name": "Katyn massacre", "event_date": "1940-04-03", "end_date": "1940-05-14", "region": "Eastern Front", "summary": "Soviet NKVD executed approximately 22,000 Polish military officers, police, and intellectuals in the Katyn forest and other sites.", "source": "curated"},
]

WAR_CRIMES = [
    {"war_event_name": "Oradour-sur-Glane massacre", "category": "massacre", "location_name": "Oradour-sur-Glane, France", "victims": "Civilians of Oradour-sur-Glane", "perpetrators": "2nd SS Panzer Division Das Reich", "death_toll": 643, "description": "German SS troops herded the entire population into the church and barns, then set them ablaze. The village was systematically destroyed.", "sources": ["French national memorial archives", "Postwar tribunal summaries"]},
    {"war_event_name": "Malmedy massacre", "category": "prisoner_execution", "location_name": "Malmedy, Belgium", "victims": "American prisoners of war, Battery B, 285th Field Artillery Observation Battalion", "perpetrators": "Kampfgruppe Peiper, 1st SS Panzer Division Leibstandarte SS Adolf Hitler", "death_toll": 84, "description": "Captured American soldiers were assembled in a field and machine-gunned by SS troops during the Battle of the Bulge.", "sources": ["U.S. Army war crimes investigation", "Dachau trials records"]},
    {"war_event_name": "Bataan Death March", "category": "forced_march", "location_name": "Bataan Peninsula, Philippines", "victims": "Filipino and American prisoners of war", "perpetrators": "Imperial Japanese Army, 14th Army", "death_toll": 10000, "description": "POWs were forced to march 65 miles in tropical heat without food or water. Those who fell were bayoneted, shot, or left to die.", "sources": ["U.S. National Archives", "International Military Tribunal for the Far East"]},
    {"war_event_name": "Rape of Nanking", "category": "mass_atrocity", "location_name": "Nanking (Nanjing), China", "victims": "Chinese civilians and disarmed combatants", "perpetrators": "Imperial Japanese Army", "death_toll": 250000, "description": "Over six weeks, Japanese soldiers committed mass murder, rape, and systematic looting. The true death toll remains disputed but was catastrophic.", "sources": ["International Military Tribunal for the Far East", "Nanjing Massacre Memorial Hall archives"]},
    {"war_event_name": "Katyn massacre", "category": "political_execution", "location_name": "Katyn Forest, USSR", "victims": "Polish military officers, police, intellectuals, and other 'anti-Soviet' leaders", "perpetrators": "Soviet NKVD", "death_toll": 22000, "description": "Systematic execution of Polish prisoners of war by Soviet secret police. The Soviet Union denied responsibility until 1990.", "sources": ["Polish Institute of National Remembrance", "Russian Federation declassified documents (1990)"]},
    {"war_event_name": "Atomic Bombing of Hiroshima", "category": "strategic_bombardment", "location_name": "Hiroshima, Japan", "victims": "Japanese civilian population of Hiroshima", "perpetrators": "United States Army Air Forces, 509th Composite Group", "death_toll": 140000, "description": "The first use of a nuclear weapon in warfare. The uranium bomb 'Little Boy' devastated the city. By the end of 1945, acute radiation syndrome and injuries brought the total death toll to approximately 140,000.", "sources": ["Hiroshima Peace Memorial Museum", "Manhattan Project archives"]},
    {"war_event_name": "Atomic Bombing of Nagasaki", "category": "strategic_bombardment", "location_name": "Nagasaki, Japan", "victims": "Japanese civilian population of Nagasaki", "perpetrators": "United States Army Air Forces, 509th Composite Group", "death_toll": 70000, "description": "The second and last nuclear weapon used in warfare. The plutonium bomb 'Fat Man' killed approximately 70,000 by the end of 1945. The bombing hastened Japan's surrender.", "sources": ["Nagasaki Atomic Bomb Museum", "Manhattan Project archives"]},
]
